<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="7" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-12T17:49:15 IST" name="Default Suite" finished-at="2024-12-12T17:49:26 IST" duration-ms="11226">
    <groups>
    </groups>
    <test started-at="2024-12-12T17:49:15 IST" name="RestAssuredAutomation" finished-at="2024-12-12T17:49:26 IST" duration-ms="11226">
      <class name="Tests.demo.CreateUserRequest">
        <test-method signature="createUser()[pri:0, instance:Tests.demo.CreateUserRequest@478ee483]" started-at="2024-12-12T17:49:26 IST" name="createUser" finished-at="2024-12-12T17:49:26 IST" duration-ms="424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
      </class> <!-- Tests.demo.CreateUserRequest -->
      <class name="Tests.demo.TestExample">
        <test-method signature="test_1()[pri:0, instance:Tests.demo.TestExample@abf688e]" started-at="2024-12-12T17:49:25 IST" name="test_1" finished-at="2024-12-12T17:49:25 IST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_1 -->
        <test-method signature="test_2()[pri:0, instance:Tests.demo.TestExample@abf688e]" started-at="2024-12-12T17:49:25 IST" name="test_2" finished-at="2024-12-12T17:49:25 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_2 -->
        <test-method signature="test_3()[pri:0, instance:Tests.demo.TestExample@abf688e]" started-at="2024-12-12T17:49:25 IST" name="test_3" finished-at="2024-12-12T17:49:26 IST" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_3 -->
      </class> <!-- Tests.demo.TestExample -->
      <class name="Tests.demo.HTTPReqResponse">
        <test-method signature="getUser()[pri:1, instance:Tests.demo.HTTPReqResponse@5e81e5ac]" started-at="2024-12-12T17:49:15 IST" name="getUser" finished-at="2024-12-12T17:49:22 IST" duration-ms="7373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUser -->
        <test-method signature="createUsers()[pri:2, instance:Tests.demo.HTTPReqResponse@5e81e5ac]" started-at="2024-12-12T17:49:22 IST" name="createUsers" finished-at="2024-12-12T17:49:24 IST" duration-ms="1466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUsers -->
        <test-method signature="updateUser()[pri:3, instance:Tests.demo.HTTPReqResponse@5e81e5ac]" started-at="2024-12-12T17:49:24 IST" name="updateUser" finished-at="2024-12-12T17:49:25 IST" depends-on-methods="Tests.demo.HTTPReqResponse.createUsers" duration-ms="555" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.lang.Integer.intValue()" because the return value of "io.restassured.internal.common.path.ObjectConverter.convertObjectTo(Object, java.lang.Class)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "io.restassured.internal.common.path.ObjectConverter.convertObjectTo(Object, java.lang.Class)" is null
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:245)
at Tests.demo.HTTPReqResponse.updateUser(HTTPReqResponse.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUser -->
        <test-method signature="deleteUser()[pri:4, instance:Tests.demo.HTTPReqResponse@5e81e5ac]" started-at="2024-12-12T17:49:25 IST" name="deleteUser" finished-at="2024-12-12T17:49:25 IST" duration-ms="437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- Tests.demo.HTTPReqResponse -->
    </test> <!-- RestAssuredAutomation -->
  </suite> <!-- Default Suite -->
</testng-results>
